### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by Drjacky** [softwaresec-labs/ACVED#2]
> The product exposes sensitive information to an actor that is not explicitly authorized to have access to that information.
Mitigation Tip : The product exposes sensitive information to an actor that is not explicitly authorized to have access to that information.
Code : else -> applyThemeMode(
Processed Code : else -> applyThemeMode(
Code Vulnerability Probability : 0.7864081765216437
Probability Breakdown of Vulnerable Code Words : [('else', 0.538470957736102), ('applyThemeMode', -0.18929641468221153)]
Predicted CWE ID Probability : 0.56
Probability Breakdown of CWE Related Vulnerable Code Words : 
More Details : https://cwe.mitre.org/data/definitions/200.html

Code:
```kotlin
when (mode) {
            AppCompatDelegate.MODE_NIGHT_NO -> applyThemeMode(
                AppCompatDelegate.MODE_NIGHT_YES,
                R.drawable.ic_mode_night_default_black
            )
            AppCompatDelegate.MODE_NIGHT_YES -> applyThemeMode(
                Settings.MODE_NIGHT_DEFAULT,
                R.drawable.ic_mode_night_no_black
            )
//SELECTED SNIPPET
            else -> applyThemeMode(
                AppCompatDelegate.MODE_NIGHT_NO,
                R.drawable.ic_mode_night_yes_black
            )
        }
//////////
```

**Comment by softwaresec-labs** [comment]
Please try with Android apps written in Java. The model trained using the latest LVDAndro dataset contains training code snipptes mainly from Apps written in Java.
